### PR TITLE
fix: Losing dconfig info when compiling and packaging

### PR DESCRIPTION
**Pull request by 18202781743**
Add adjust for linux when compile.
  Add `D_DSG_APP_DATA_FALLBACK` macro when packaging.
 see the commit: 7b13e5c4b867fcbdcc50f5e409b0c8726496b7e5

Log: none
Influence: none
Change-Id: Ie047dbd2d8158ed5242dfb5bcc7fa4e02ee1d925

### CODE REVIEW

**Comment by 18202781743** [comment]
@Decodetalkers

**Comment by Decodetalkers** [comment]
dbus文件下面的xml文件不需要了吗。。

**Review by kegechen — APPROVED** [review]

**Pull request merged**
